### ISSUE TITLE
TypeError [ERR_INVALID_CALLBACK]: Callback must be a function

### ISSUE THREAD

**Issue by deanvaessen** [kvenux/nodegcs#1]
Hi,

Awesome project! Just ran into a little snag and hoped you could shed some light on this.
I'm faced with this error:

```
Connectedted    STABILIZE       DISARM  SatNum: 0       HDOP: 0 VDOP: 0         Battery: 12.587V
Pitch: 0        Roll: 0 Yaw: 0  Lat: 0          Lng: 0
X-Speed: 0m/s   Y-Speed: 0m/s   Z-Speed: 0m/s   Height: 0m
>> connection regained
>> ARMING MOTORS
>> Initialising APM...
>> command success
>> DISARMING MOTORS
➜ nodegcs v1.0
timers.js:425
    throw new errors.TypeError('ERR_INVALID_CALLBACK');
    ^

TypeError [ERR_INVALID_CALLBACK]: Callback must be a function
    at setTimeout (timers.js:425:11)
    at Timeout.send_default_datastream [as _onTimeout] (D:\Workshop\Tech\Programming\Projects\Professional\MaverickMatryoshka\2018\sadie\project\lib\controller_mav\mavlink_connection.js:720:9)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:267:5)
```

Steps to reproduce: 

1. node nodegcs
2. start
3. arm
4. wait for a few seconds
5. crash

The only thing I changed was upgrade to v6 of the serialport dependency as v5 didn't work for my node version.

If it helps, I am using sitl as the simulator, as you suggested (though I installed with `pip install dronekit-sitl -UI` as per instructions on their website).

**Comment by deanvaessen** [comment]
Confirmed! Many thanks! :tada:
