### ISSUE TITLE
Connecti via serial using Pixfalcon

### ISSUE THREAD

**Issue by thirafi98** [kvenux/nodegcs#2]
hello, i was trying testing your project using pixfalcon, as you said before if i want to connect via serial using this : `start /dev/cu.usbserial-A503UTCT 115200` but when i try to use COM as serialport, there's an error like this :
 mav_port = new SerialPort(connection_path, {
               ^
TypeError: SerialPort is not a constructor
    at Timeout.connect_serial [as _onTimeout] (D:\Materi Lab\nodegcs-master\mavlink_connection.js:538:16)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5)

how do i fix this on your code, thank you

**Comment by deanvaessen** [comment]
Just chiming in that I also got a similar issue when I ran "stop" after being connected over TCP (though I think it shouldn't even call that function in TCP mode as it's a function for serial connections if I understand correctly):

```
TypeError: mav_port.close is not a function
    at Object.pause_serial (D:\Workshop\Tech\Programming\Projects\Professional\MaverickMatryoshka\2018\sadie\project\lib\controller_mav\mavlink_connection.js:912:14)
    at ReadStream.<anonymous> (D:\Workshop\Tech\Programming\Projects\Professional\MaverickMatryoshka\2018\sadie\project\lib\controller_mav\nodegcs.js:248:13)
    at ReadStream.emit (events.js:180:13)
    at addChunk (_stream_readable.js:269:12)
    at readableAddChunk (_stream_readable.js:256:11)
    at ReadStream.Readable.push (_stream_readable.js:213:10)
    at TTY.onread (net.js:578:20)
```

**Comment by kvenux** [comment]
@thirafi98 This bug is caused by new version of serialport. I have upgrade serialport to the newest one(6.2.0) and make some modification to adapt to the new version. e.g. isOpen is a property instead of a function since 5.x.
@deanvaessen I have adjusted the closing method for net.Socket.

**Comment by thirafi98** [comment]
alrite thx for the help, i just figure it out like few days ago hahaha
